UPDATE ALUNOS SET DTNASCIMENTO = '2006-02-10' WHERE NOME = 'Ana Paula de Souza'

CREATE TABLE BOLSAS 
(
    ID_BOLSA INT CONSTRAINT PK_BOLSA PRIMARY KEY,
    MATRICULA INT,
    VALOR MONEY

)

ALTER TABLE BOLSAS ADD CONSTRAINT FK_BOLSAS_ALUNOS FOREIGN KEY (MATRICULA) 
REFERENCES ALUNOS (MATRICULA)

SELECT * FROM BOLSAS

INSERT BOLSAS (ID_BOLSA, MATRICULA, VALOR)
VALUES (12345, 1144008644, 1405.00)

CREATE TABLE PESSOAS 
(
    CPF INT PRIMARY KEY,
    NOME CHAR,
    DATA_NASCIMENTO DATE
)

SELECT * FROM PESSOAS